### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lCyPh3r** [ItsMerkz/Tellonym.me-Account-Creator#3]
when i run the main.py

says :

Traceback (most recent call last):
  File "C:\Users\Darkness\Downloads\Tellonym.me-Account-Creator-main\main.py", line 39, in <module>
    creator().main()
  File "C:\Users\Darkness\Downloads\Tellonym.me-Account-Creator-main\main.py", line 10, in __init__
    self.password = config['aaaa189972$']
KeyError: 'aaaa189972$'

**Comment by ItsMerkz** [comment]
yeah, dont change the main.py file at all, just change the config, you changed the config in main.py you need to change the file config.json and its contents!
